package negocio.entities;

public enum TipoCurso {
	MASTER,
	EXPERTO,
	ESPECIALISTA,
	FORMACION_AVANZADA,
	FORMACION_CONTINUA,
	MICROCREDENCIALES,
	CORTA_DURACION,
	CURSOS_DE_VERANO,
	FORMACION_DE_MAYORES
}